#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReMinder.Resource", IsApplication=true)]

namespace ReMinder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::ReMinder.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int planets_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int action_bar_background = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int textColor = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_right_big = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int checkbox_off = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int checkbox_on = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int checkmark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int chevron = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CreateAccountSelector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int crossmark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int email = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_new = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_overflow = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int login_bkg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int logo_login = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int password = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int qna_bkg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int QuestionTextView = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int register_bkg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int reminder_icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int TransparentButton = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int TransparentButtonPressed = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int TransparentButtonSelected = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int user = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090009
			public const int btnClose = 2131296265;
			
			// aapt resource value: 0x7f090005
			public const int btnLogin = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int btnNextQuestion = 2131296263;
			
			// aapt resource value: 0x7f09000e
			public const int btnRegister = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int imgLoginLogo = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int listAnswers = 2131296264;
			
			// aapt resource value: 0x7f090013
			public const int listView1 = 2131296275;
			
			// aapt resource value: 0x7f090016
			public const int mainMenu = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int overflowMenuItem = 2131296279;
			
			// aapt resource value: 0x7f090011
			public const int spinner1 = 2131296273;
			
			// aapt resource value: 0x7f09000f
			public const int textView1 = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int textView2 = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int textView3 = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int textView4 = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int toggleButton1 = 2131296277;
			
			// aapt resource value: 0x7f090001
			public const int txtEmail = 2131296257;
			
			// aapt resource value: 0x7f09000a
			public const int txtNewEmail = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int txtNewPassword = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int txtNewUsername = 2131296267;
			
			// aapt resource value: 0x7f090002
			public const int txtPassword = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int txtQuestion = 2131296262;
			
			// aapt resource value: 0x7f09000d
			public const int txtRepeatPassword = 2131296269;
			
			// aapt resource value: 0x7f090004
			public const int txtViewPassword = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int txtViewRegister = 2131296259;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Question = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Register = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int mainMenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int ApplicationName = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int Close = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Continue = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int CreateAccount = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int EmailHint = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int EmailValidationError = 2130968585;
			
			// aapt resource value: 0x7f040011
			public const int ErrorWhileLogin = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int ErrorWhileRegistration = 2130968594;
			
			// aapt resource value: 0x7f040001
			public const int Login = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int NotImplemented = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int Password = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int PasswordHint = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int PasswordUnMatchValidationError = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int PasswordValidationError = 2130968591;
			
			// aapt resource value: 0x7f040002
			public const int Register = 2130968578;
			
			// aapt resource value: 0x7f04000e
			public const int RepeatPasswordHint = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int UsernameHint = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int UsernameValidationError = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int ReMinder_ActionBar = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int ReMinderTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
