#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android.Resource", IsApplication=true)]

namespace Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int menu_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_right_big = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int checkbox_off = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int checkbox_on = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int checkmark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int chevron = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int crossmark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int email = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_new = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_overflow = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int login_bkg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int logo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logo_login = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int password = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int qna_bkg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int register_bkg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int reminder_icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int user = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int btnContinue = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int btnFinish = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int btnLogin = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int imgLoginLogo = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int mainMenu = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int overflowMenuItem = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int txtEmail = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int txtPassword = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int txtViewPassword = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int txtViewRegister = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Question = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Settings = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int mainMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int ApplicationName = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int Continue = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int EmailHint = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int EmailValidationError = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int ErrorWhileLogin = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int Finish = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int Login = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int Password = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int PasswordHint = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int PasswordValidationError = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int Register = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int ReMinderTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
